#!/usr/bin/env python3

"""
Audit the aggregated Gate-1 H0 optimizer-diagnostics table.

PURPOSE
    `gate1_oracle_diagnostics.csv` (produced by
    `aggregate_gate1_oracle_diagnostics.py`) combines three distinct
    local Gate-1 runs into one table. Before that table is used as
    input to any adaptive-H0 analysis, this script verifies that the
    three runs are unambiguously distinguishable and internally
    consistent, and reports the structural facts an analyst needs
    before trusting the table:

    - final columns and row counts per `source` (run);
    - number of events and semantic strategies per `source`, using
      BOTH the raw (mode, label) pair and the canonical
      (mode, strategy_id) pair;
    - whether the (mode, start_slot) -> label mapping is constant
      across events within each `source` (verified empirically, not
      assumed), and separately whether every (mode, strategy_id) pair
      covers all events in that source (i.e. strategy_id is a total,
      consistent key);
    - duplicate or missing (mode, catalog_row, start_slot) /
      (mode, catalog_row, label) / (mode, catalog_row, strategy_id)
      keys per `source`;
    - distribution of `optimizer_success` and `optimizer_active_mask`,
      reported SEPARATELY as:
        * per_fit_*   -- over every individual H0 optimization
                         (one row = one start);
        * winner_*    -- over only the per-(source, catalog_row)
                         minimum-chi2 row (i.e. one row per event,
                         the start that "wins" for that event within
                         that source/run).
      These two views answer different questions: per_fit_* describes
      how often an individual start lands on a bound; winner_*
      describes how often the SELECTED solution for an event does.
      A high per_fit_rho_active_rate does not by itself imply the
      rho domain is insufficient (see interpretation notes in
      ADAPTIVE_H0_ANALYSIS.md) -- that question is about winners, not
      individual starts.
    - a hard integrity check per `source`: `hypothesis` is `"H0"`
      everywhere, `status` is `"success"` everywhere usable rows are
      expected to be usable, `chi2`/`t0`/`u0`/`tE`/`rho` are finite on
      every `status=="success"` row, `h0_start_plan` and
      `t0_margin_factor` match the run's own declared values with no
      exceptions, and the set of `catalog_row` values is exactly the
      100-event `extreme100` reference set (no extra, none missing).
      THIS CHECK RAISES `RuntimeError` on any violation -- it is not
      print-only, because a silent structural violation here would
      corrupt every downstream Phase A/B result built on this table.

INPUTS
    validation/bounds_convergence/results/gate1_oracle_diagnostics.csv
        (produced by aggregate_gate1_oracle_diagnostics.py; not
        regenerated by this script)

OUTPUTS
    validation/bounds_convergence/results/
        gate1_oracle_diagnostics_audit_by_source.csv
            one row per `source`: row/event/strategy counts (raw
            label and canonical strategy_id), the hard integrity
            check's counters (hypothesis/status/finiteness/
            h0_start_plan/t0_margin_factor/catalog_row-set), the same
            duplicate/missing counts, start_slot/strategy_id
            consistency flags, and per_fit_* / winner_* optimizer
            diagnostics.
        gate1_oracle_diagnostics_audit_start_slot_map.csv
            one row per (source, mode, start_slot): the set of
            distinct labels observed at that slot across events,
            and whether that set has size 1 (i.e. the slot is
            label-stable for that source/mode).
        gate1_oracle_diagnostics_audit_strategy_id_coverage.csv
            one row per (source, mode, strategy_id): how many
            distinct events that strategy_id appears for in that
            source, and whether that equals the source's total event
            count (i.e. strategy_id is present for every event, never
            silently dropped for some).

WHAT QUESTION THIS ANSWERS
    "Is gate1_oracle_diagnostics.csv structurally sound, and can
    (mode, strategy_id) be trusted as a strategy key that is stable
    across events, separately for each of the three source runs?"

ORACLE USAGE
    None. This is a pure data-integrity audit; it does not compare
    any run against another run's chi2, and does not use any
    oracle/validation-only information. The winner_* statistics use
    only the MINIMUM CHI2 WITHIN THE SAME SOURCE/RUN (i.e. the best
    of that run's own starts for that event) -- this is not the
    52-fit or 5-fit oracle from another source, and is not compared
    against it here.

STATUS
    Development / documentation tooling. Not a scientific validation
    result. Referenced from ADAPTIVE_H0_ANALYSIS.md, Phase 0
    (table audit), which precedes the Phase A/B adaptive analysis.
"""

from __future__ import annotations

import ast
from pathlib import Path

import numpy as np
import pandas as pd


RESULTS_DIR = Path(
    "Parallax_LSST/lsstmonts_catalog_sedighe/"
    "validation/bounds_convergence/results"
)

IN_PATH = RESULTS_DIR / "gate1_oracle_diagnostics.csv"

# Same manifest aggregate_gate1_oracle_diagnostics.py uses to define
# the extreme100 event set, restated here (not imported) so this
# audit does not silently rely on import-time coupling to that
# script.
MANIFEST = Path(
    "Parallax_LSST/lsstmonts_catalog_sedighe/"
    "validation/bounds_convergence/data/"
    "extreme100_refit_manifest.csv"
)

# Expected h0_start_plan / t0_margin_factor per source -- restated
# from ROOTS in aggregate_gate1_oracle_diagnostics.py for the same
# import-decoupling reason as EXPECTED_PER_MODE below.
EXPECTED_RUN_METADATA = {
    "gate1_oracle_52": {
        "h0_start_plan": "all",
        "t0_margin_factor": 0.0,
    },
    "gate1_final18_base_t0margin0": {
        "h0_start_plan": "gate1_final18",
        "t0_margin_factor": 0.0,
    },
    "gate1_final18_rescue_t0margin0.25": {
        "h0_start_plan": "gate1_final18",
        "t0_margin_factor": 0.25,
    },
}

OUT_BY_SOURCE = (
    RESULTS_DIR / "gate1_oracle_diagnostics_audit_by_source.csv"
)
OUT_SLOT_MAP = (
    RESULTS_DIR
    / "gate1_oracle_diagnostics_audit_start_slot_map.csv"
)
OUT_STRATEGY_COVERAGE = (
    RESULTS_DIR
    / "gate1_oracle_diagnostics_audit_strategy_id_coverage.csv"
)

# Expected number of distinct (mode, strategy_id) pairs per source
# (i.e. the size of the start plan): 4 modes x 13 canonical starts
# for the 52-fit oracle; 18 for each gate1_final18 run (3 physical +
# 6 log_te + 8 log_rho + 1 log_te_rho, see gate1_plan in
# run_bounds_audit_refit_core.py:2585-2615).
EXPECTED_N_STRATEGY_IDS = {
    "gate1_oracle_52": 52,
    "gate1_final18_base_t0margin0": 18,
    "gate1_final18_rescue_t0margin0.25": 18,
}

# Expected number of (mode, start_slot) rows per event, per source.
# These are the same expectations encoded in ROOTS[...]["expected"]
# inside aggregate_gate1_oracle_diagnostics.py, restated here so this
# audit does not silently rely on import-time coupling to that
# script.
EXPECTED_PER_MODE = {
    "gate1_oracle_52": {
        "physical": 13,
        "log_te": 13,
        "log_rho": 13,
        "log_te_rho": 13,
    },
    "gate1_final18_base_t0margin0": {
        "physical": 3,
        "log_te": 6,
        "log_rho": 8,
        "log_te_rho": 1,
    },
    "gate1_final18_rescue_t0margin0.25": {
        "physical": 3,
        "log_te": 6,
        "log_rho": 8,
        "log_te_rho": 1,
    },
}


def _parse_active_mask(raw) -> tuple[int, ...] | None:

    if not isinstance(raw, str):
        return None

    try:
        val = ast.literal_eval(raw)
    except (ValueError, SyntaxError):
        return None

    return tuple(int(x) for x in val)


def audit_columns(df: pd.DataFrame) -> None:

    print("=" * 70)
    print("1. FINAL COLUMNS")
    print("=" * 70)
    for c in df.columns:
        print(f"  - {c} ({df[c].dtype})")
    print()


def audit_rows_per_source(df: pd.DataFrame) -> pd.DataFrame:

    print("=" * 70)
    print("2-3. ROWS / EVENTS PER SOURCE")
    print("=" * 70)

    rows_per_source = df.groupby("source").size()
    events_per_source = df.groupby("source")["catalog_row"].nunique()

    for source in rows_per_source.index:
        print(
            f"  {source}: "
            f"n_rows={rows_per_source[source]}, "
            f"n_events={events_per_source[source]}"
        )
    print()

    return pd.DataFrame(
        {
            "n_rows": rows_per_source,
            "n_events": events_per_source,
        }
    )


def _read_reference_events() -> set[int]:

    manifest = pd.read_csv(MANIFEST)

    return set(
        pd.to_numeric(manifest["catalog_row"], errors="raise")
        .astype(int)
        .drop_duplicates()
        .tolist()
    )


def audit_integrity(df: pd.DataFrame) -> pd.DataFrame:
    """
    Hard structural-integrity check, per source. Unlike the other
    audit_* functions (which report facts for the analyst to read),
    every violation checked here RAISES RuntimeError immediately --
    these are invariants gate1_oracle_diagnostics.csv must hold for
    it to be safely usable as Phase A/B input, not just facts to note.
    """

    print("=" * 70)
    print(
        "2b. HARD INTEGRITY CHECK (hypothesis, status, finiteness, "
        "h0_start_plan, t0_margin_factor, catalog_row set)"
    )
    print("=" * 70)

    reference_events = _read_reference_events()

    out = {}

    for source, g in df.groupby("source"):

        errors: list[str] = []

        # --- hypothesis -------------------------------------------
        hyp_values = sorted(g["hypothesis"].unique().tolist())
        if hyp_values != ["H0"]:
            errors.append(
                "hypothesis values != ['H0']: "
                f"{hyp_values}"
            )

        # --- status / finiteness on usable (status=='success')
        # rows ------------------------------------------------------
        status_counts = (
            g["status"].value_counts().to_dict()
        )
        n_success = int(status_counts.get("success", 0))
        n_non_success = int(len(g) - n_success)

        if n_non_success:
            errors.append(
                f"{n_non_success} rows have status != 'success': "
                f"{status_counts}"
            )

        success_rows = g[g["status"] == "success"]

        n_nonfinite = {}
        for col in ["chi2", "t0", "u0", "tE", "rho"]:
            n_bad = int(
                (~np.isfinite(success_rows[col])).sum()
            )
            n_nonfinite[col] = n_bad
            if n_bad:
                errors.append(
                    f"{n_bad} status=='success' rows have "
                    f"non-finite {col}"
                )

        # --- h0_start_plan / t0_margin_factor consistency ----------
        expected = EXPECTED_RUN_METADATA.get(source)
        n_plan_mismatch = 0
        n_margin_mismatch = 0

        if expected is None:
            errors.append(
                f"no EXPECTED_RUN_METADATA entry for source "
                f"{source!r}"
            )
        else:
            n_plan_mismatch = int(
                (g["h0_start_plan"] != expected["h0_start_plan"]).sum()
            )
            if n_plan_mismatch:
                errors.append(
                    f"{n_plan_mismatch} rows have h0_start_plan != "
                    f"{expected['h0_start_plan']!r}"
                )

            n_margin_mismatch = int(
                (
                    ~np.isclose(
                        g["t0_margin_factor"].astype(float),
                        expected["t0_margin_factor"],
                        rtol=0.0,
                        atol=1.0e-12,
                    )
                ).sum()
            )
            if n_margin_mismatch:
                errors.append(
                    f"{n_margin_mismatch} rows have t0_margin_factor "
                    f"!= {expected['t0_margin_factor']!r}"
                )

        # --- catalog_row set exactly the extreme100 reference ------
        observed_events = set(g["catalog_row"].unique().tolist())
        extra_events = observed_events - reference_events
        missing_events = reference_events - observed_events

        if extra_events or missing_events:
            errors.append(
                f"catalog_row set mismatch vs. extreme100 reference: "
                f"{len(extra_events)} extra "
                f"{sorted(extra_events)[:10]}, "
                f"{len(missing_events)} missing "
                f"{sorted(missing_events)[:10]}"
            )

        print(
            f"  {source}: hypothesis={hyp_values}, "
            f"status_counts={status_counts}, "
            f"n_nonfinite={n_nonfinite}, "
            f"h0_start_plan_mismatches={n_plan_mismatch}, "
            f"t0_margin_factor_mismatches={n_margin_mismatch}, "
            f"n_events_observed={len(observed_events)}, "
            f"n_extra_events={len(extra_events)}, "
            f"n_missing_events={len(missing_events)}"
        )

        if errors:
            raise RuntimeError(
                "Structural integrity violation(s) in "
                f"gate1_oracle_diagnostics.csv for source={source!r}: "
                + "; ".join(errors)
            )

        out[source] = {
            "n_hypothesis_values": len(hyp_values),
            "n_status_success": n_success,
            "n_status_non_success": n_non_success,
            "n_nonfinite_chi2": n_nonfinite["chi2"],
            "n_nonfinite_t0": n_nonfinite["t0"],
            "n_nonfinite_u0": n_nonfinite["u0"],
            "n_nonfinite_tE": n_nonfinite["tE"],
            "n_nonfinite_rho": n_nonfinite["rho"],
            "n_h0_start_plan_mismatches": n_plan_mismatch,
            "n_t0_margin_factor_mismatches": n_margin_mismatch,
            "n_events_observed": len(observed_events),
            "n_extra_events_vs_reference": len(extra_events),
            "n_missing_events_vs_reference": len(missing_events),
            "catalog_row_set_matches_reference": (
                not extra_events and not missing_events
            ),
        }

    print()

    return pd.DataFrame(out).T


def audit_semantic_strategies(
    df: pd.DataFrame,
) -> tuple[pd.Series, pd.Series]:

    print("=" * 70)
    print(
        "4. DISTINCT (mode, label) vs (mode, strategy_id) "
        "PER SOURCE"
    )
    print("=" * 70)

    print(
        "    NOTE: for gate1_oracle_52 the RAW label text embeds "
        "event-specific numeric values (e.g. an event's own old_H0 "
        "or truth rho) for 3/13 slots per mode, so its distinct-label "
        "count does not equal the true number of reusable named "
        "strategies (52). strategy_id is the canonical, "
        "event-independent key (see aggregate_gate1_oracle_"
        "diagnostics.py module docstring) and is expected to have "
        "exactly 52 distinct (mode, strategy_id) pairs for "
        "gate1_oracle_52. For the gate1_final18 sources, label is "
        "already event-independent (fixed constant or the literal "
        "tag 'truth'), so both counts are expected to equal the plan "
        "size (18)."
    )

    n_labels = df.groupby("source").apply(
        lambda g: g[["mode", "label"]]
        .drop_duplicates()
        .shape[0],
        include_groups=False,
    )

    n_strategy_ids = df.groupby("source").apply(
        lambda g: g[["mode", "strategy_id"]]
        .drop_duplicates()
        .shape[0],
        include_groups=False,
    )

    for source in n_labels.index:
        expected = EXPECTED_N_STRATEGY_IDS.get(source)
        n_sid = int(n_strategy_ids[source])
        ok = "OK" if n_sid == expected else "MISMATCH"
        print(
            f"  {source}: "
            f"{int(n_labels[source])} distinct (mode, label) pairs, "
            f"{n_sid} distinct (mode, strategy_id) pairs "
            f"(expected {expected}) -> {ok}"
        )
    print()

    return n_labels, n_strategy_ids


def audit_strategy_id_coverage(
    df: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.Series]:

    print("=" * 70)
    print(
        "4b. DOES EVERY (mode, strategy_id) COVER ALL EVENTS?"
    )
    print("=" * 70)

    n_events_by_source = df.groupby("source")["catalog_row"].nunique()

    records = []

    for (source, mode, sid), g in df.groupby(
        ["source", "mode", "strategy_id"]
    ):
        n_cov = g["catalog_row"].nunique()
        n_events = int(n_events_by_source[source])
        records.append(
            {
                "source": source,
                "mode": mode,
                "strategy_id": sid,
                "n_events_covering_strategy_id": n_cov,
                "n_events_in_source": n_events,
                "full_coverage": n_cov == n_events,
            }
        )

    coverage = pd.DataFrame.from_records(records).sort_values(
        ["source", "mode", "strategy_id"]
    )

    n_incomplete_by_source = (
        coverage[~coverage["full_coverage"]]
        .groupby("source")
        .size()
    )
    n_sid_by_source = coverage.groupby("source").size()

    for source in n_sid_by_source.index:
        n_incomplete = int(n_incomplete_by_source.get(source, 0))
        n_total = int(n_sid_by_source[source])
        full = n_incomplete == 0
        print(
            f"  {source}: "
            f"{n_total - n_incomplete}/{n_total} (mode, strategy_id) "
            f"pairs cover all events -> strategy_id total "
            f"coverage: {full}"
        )
    print()

    full_coverage_flag = (
        n_incomplete_by_source.reindex(
            n_sid_by_source.index, fill_value=0
        )
        == 0
    )

    return coverage, full_coverage_flag


def audit_start_slot_label_consistency(
    df: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.Series]:

    print("=" * 70)
    print(
        "5. IS (mode, start_slot) -> label CONSTANT ACROSS EVENTS?"
    )
    print("=" * 70)

    records = []

    for (source, mode, slot), g in df.groupby(
        ["source", "mode", "start_slot"]
    ):
        labels = sorted(g["label"].unique())
        records.append(
            {
                "source": source,
                "mode": mode,
                "start_slot": slot,
                "n_distinct_labels": len(labels),
                "n_events_covering_slot": g["catalog_row"].nunique(),
                "example_labels": (
                    labels[0]
                    if len(labels) == 1
                    else " | ".join(labels[:5])
                    + (" | ..." if len(labels) > 5 else "")
                ),
            }
        )

    slot_map = pd.DataFrame.from_records(records).sort_values(
        ["source", "mode", "start_slot"]
    )

    n_unstable_by_source = (
        slot_map[slot_map["n_distinct_labels"] > 1]
        .groupby("source")
        .size()
    )
    n_slots_by_source = slot_map.groupby("source").size()

    for source in n_slots_by_source.index:
        n_unstable = int(n_unstable_by_source.get(source, 0))
        n_total = int(n_slots_by_source[source])
        stable = n_unstable == 0
        print(
            f"  {source}: "
            f"{n_total - n_unstable}/{n_total} (mode, start_slot) "
            f"combinations map to a single label across events "
            f"-> start_slot->label CONSTANT: {stable}"
        )

    print()

    stability_flag = (
        n_unstable_by_source.reindex(
            n_slots_by_source.index, fill_value=0
        )
        == 0
    )

    return slot_map, stability_flag


def audit_duplicates_and_missing(df: pd.DataFrame) -> pd.DataFrame:

    print("=" * 70)
    print("6. DUPLICATES / MISSING (mode, catalog_row, start_slot)")
    print("=" * 70)

    out = {}

    for source, g in df.groupby("source"):

        dup_slot = g.duplicated(
            subset=["mode", "catalog_row", "start_slot"]
        ).sum()

        dup_label = g.duplicated(
            subset=["mode", "catalog_row", "label"]
        ).sum()

        dup_strategy_id = g.duplicated(
            subset=["mode", "catalog_row", "strategy_id"]
        ).sum()

        expected = EXPECTED_PER_MODE.get(source, {})

        counts = (
            g.groupby(["mode", "catalog_row"]).size().rename("n")
        )

        n_missing_or_short = 0
        n_over = 0

        for (mode, row), n in counts.items():
            exp_n = expected.get(mode)
            if exp_n is None:
                continue
            if n < exp_n:
                n_missing_or_short += 1
            elif n > exp_n:
                n_over += 1

        events = g["catalog_row"].unique()
        modes = g["mode"].unique()
        full_index = pd.MultiIndex.from_product(
            [modes, events], names=["mode", "catalog_row"]
        )
        present_index = counts.index
        n_fully_absent = len(
            full_index.difference(present_index)
        )

        print(
            f"  {source}: "
            f"dup(mode,row,start_slot)={dup_slot}, "
            f"dup(mode,row,label)={dup_label}, "
            f"dup(mode,row,strategy_id)={dup_strategy_id}, "
            f"(mode,row) with row-count < expected={n_missing_or_short}, "
            f"(mode,row) with row-count > expected={n_over}, "
            f"(mode,row) combinations entirely absent="
            f"{n_fully_absent}"
        )

        out[source] = {
            "n_duplicate_mode_row_slot": int(dup_slot),
            "n_duplicate_mode_row_label": int(dup_label),
            "n_duplicate_mode_row_strategy_id": int(dup_strategy_id),
            "n_mode_row_short_of_expected": int(n_missing_or_short),
            "n_mode_row_over_expected": int(n_over),
            "n_mode_row_fully_absent": int(n_fully_absent),
        }

    print()

    return pd.DataFrame(out).T


def _optimizer_rate_block(g: pd.DataFrame) -> dict:
    """
    Compute optimizer_success rate and active_mask rates (overall
    and per H0 component t0/u0/tE/rho) over whatever subset of rows
    `g` contains. Called once for "every fit" and once for "only the
    per-event winner within this source" -- see module docstring for
    why these must be kept separate.
    """

    n = len(g)

    n_success = int(g["optimizer_success"].astype(bool).sum())

    masks = g["optimizer_active_mask"].apply(_parse_active_mask)

    n_parseable = int(masks.notna().sum())

    def _any_active(m):
        return m is not None and any(x != 0 for x in m)

    n_any_active = int(masks.apply(_any_active).sum())

    # H0 rows only have 4 nonlinear parameters (t0, u0, tE, rho);
    # component-wise active-bound rate.
    h0_masks = masks[
        masks.apply(lambda m: m is not None and len(m) == 4)
    ]

    n_h0_masks = len(h0_masks)

    def _component_active_rate(idx):
        if n_h0_masks == 0:
            return float("nan")
        return float(
            h0_masks.apply(lambda m: m[idx] != 0).sum()
        ) / n_h0_masks

    return {
        "n": n,
        "success_rate": n_success / n if n else float("nan"),
        "n_active_mask_parseable": n_parseable,
        "any_bound_active_rate": (
            n_any_active / n_parseable
            if n_parseable
            else float("nan")
        ),
        "n_h0_4component_masks": n_h0_masks,
        "t0_active_rate": _component_active_rate(0),
        "u0_active_rate": _component_active_rate(1),
        "tE_active_rate": _component_active_rate(2),
        "rho_active_rate": _component_active_rate(3),
    }


def audit_optimizer_diagnostics(df: pd.DataFrame) -> pd.DataFrame:

    print("=" * 70)
    print(
        "7. optimizer_success / optimizer_active_mask BY SOURCE "
        "-- per_fit vs winner"
    )
    print("=" * 70)

    print(
        "    per_fit_*  : computed over every individual H0 start.\n"
        "    winner_*   : computed over only the minimum-chi2 row "
        "per (source, catalog_row) -- i.e. the start that wins for "
        "that event WITHIN THIS SOURCE's own starts. This is not "
        "the cross-source 52-fit or 5-fit oracle; it only answers "
        "'what does this run's own selected solution look like', "
        "per source."
    )

    winners = df.loc[
        df.groupby(["source", "catalog_row"])["chi2"].idxmin()
    ]

    out = {}

    for source, g in df.groupby("source"):

        per_fit = _optimizer_rate_block(g)
        winner = _optimizer_rate_block(
            winners[winners["source"] == source]
        )

        print(f"  {source}:")
        print(
            "      per_fit: n="
            f"{per_fit['n']}, success_rate="
            f"{per_fit['success_rate']:.4f}, "
            "any_bound_active_rate="
            f"{per_fit['any_bound_active_rate']:.4f}, "
            f"t0={per_fit['t0_active_rate']:.4f}, "
            f"u0={per_fit['u0_active_rate']:.4f}, "
            f"tE={per_fit['tE_active_rate']:.4f}, "
            f"rho={per_fit['rho_active_rate']:.4f}"
        )
        print(
            "      winner : n="
            f"{winner['n']}, success_rate="
            f"{winner['success_rate']:.4f}, "
            "any_bound_active_rate="
            f"{winner['any_bound_active_rate']:.4f}, "
            f"t0={winner['t0_active_rate']:.4f}, "
            f"u0={winner['u0_active_rate']:.4f}, "
            f"tE={winner['tE_active_rate']:.4f}, "
            f"rho={winner['rho_active_rate']:.4f}"
        )

        out[source] = {
            "n_rows": per_fit["n"],
            "per_fit_optimizer_success_rate": per_fit[
                "success_rate"
            ],
            "per_fit_any_bound_active_rate": per_fit[
                "any_bound_active_rate"
            ],
            "per_fit_t0_active_rate": per_fit["t0_active_rate"],
            "per_fit_u0_active_rate": per_fit["u0_active_rate"],
            "per_fit_tE_active_rate": per_fit["tE_active_rate"],
            "per_fit_rho_active_rate": per_fit["rho_active_rate"],
            "n_events_for_winner": winner["n"],
            "winner_optimizer_success_rate": winner[
                "success_rate"
            ],
            "winner_any_bound_active_rate": winner[
                "any_bound_active_rate"
            ],
            "winner_t0_active_rate": winner["t0_active_rate"],
            "winner_u0_active_rate": winner["u0_active_rate"],
            "winner_tE_active_rate": winner["tE_active_rate"],
            "winner_rho_active_rate": winner["rho_active_rate"],
        }

    print()

    return pd.DataFrame(out).T


def main() -> None:

    df = pd.read_csv(IN_PATH)

    audit_columns(df)

    rows_events = audit_rows_per_source(df)
    integrity = audit_integrity(df)
    n_labels, n_strategy_ids = audit_semantic_strategies(df)
    strategy_coverage, strategy_full_coverage_flag = (
        audit_strategy_id_coverage(df)
    )
    slot_map, stability_flag = (
        audit_start_slot_label_consistency(df)
    )
    dup_missing = audit_duplicates_and_missing(df)
    optimizer_stats = audit_optimizer_diagnostics(df)

    summary = (
        rows_events.join(integrity)
        .join(
            n_labels.rename("n_distinct_mode_label_pairs")
        )
        .join(
            n_strategy_ids.rename(
                "n_distinct_mode_strategy_id_pairs"
            )
        )
        .join(
            strategy_full_coverage_flag.rename(
                "strategy_id_covers_all_events"
            )
        )
        .join(
            stability_flag.rename(
                "start_slot_to_label_constant_across_events"
            )
        )
        .join(dup_missing)
        .join(optimizer_stats.drop(columns=["n_rows"]))
    )

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    summary.to_csv(OUT_BY_SOURCE, index_label="source")
    slot_map.to_csv(OUT_SLOT_MAP, index=False)
    strategy_coverage.to_csv(OUT_STRATEGY_COVERAGE, index=False)

    print("=" * 70)
    print("WROTE")
    print("=" * 70)
    print(f"  {OUT_BY_SOURCE}")
    print(f"  {OUT_SLOT_MAP}")
    print(f"  {OUT_STRATEGY_COVERAGE}")


if __name__ == "__main__":
    main()
