#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Empirical coverage of the Monte-Carlo propagated central 68% interval
for |pi_E| in the STRICTLY POSITIVE H1 LRT population.

NO simulation.
NO fitting.
NO new Monte Carlo sampling.

Input
-----
Uses the event-level q16, q50, q84 values already generated by

    22_piE_amplitude_uncertainty_mc_vs_truth.py

For each event we test whether

    q16_MC <= |pi_E,true| <= q84_MC.

If the local multivariate-normal covariance approximation and its
transformation to |pi_E| are well calibrated, the central 68% interval
would ideally have approximately 68% empirical coverage.

Important
---------
The comparison is made separately for:

    confused_fspl_no_parallax
    parallax_detected

so these are CLASS-CONDITIONAL coverage measurements.

Because the classes are themselves selected using the LRT statistic,
68% is a useful calibration reference, not a guaranteed exact
frequentist coverage level after selection.
"""

from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import sys as _paper_sys
from pathlib import Path as _PaperPath

_PAPER_LRT_DIR = next(
    parent
    for parent in _PaperPath(__file__).resolve().parents
    if parent.name == "lrt"
)
_paper_sys.path.insert(
    0,
    str(_PAPER_LRT_DIR / "plotting"),
)
from paper_style import (
    apply_paper_style,
    label_panels,
    save_pdf_companion,
)

apply_paper_style()


# ============================================================
# Paths
# ============================================================

ROOT = Path(__file__).resolve().parents[3]

INPUT = (
    ROOT
    / "analysis"
    / "lrt"
    / "results"
    / "characterization"
    / "22_piE_amplitude_uncertainty_mc_vs_truth"
    / "piE_amplitude_mc_event_intervals.parquet"
)

FIGURE_DIR = (
    ROOT
    / "analysis"
    / "lrt"
    / "figures"
    / "characterization"
    / "23_piE_amplitude_mc_coverage_vs_truth"
)

RESULT_DIR = (
    ROOT
    / "analysis"
    / "lrt"
    / "results"
    / "characterization"
    / "23_piE_amplitude_mc_coverage_vs_truth"
)

FIGURE = (
    FIGURE_DIR
    / "piE_amplitude_mc_coverage_vs_truth.png"
)

TABLE = (
    RESULT_DIR
    / "piE_amplitude_mc_coverage_vs_truth_bins.csv"
)


# ============================================================
# Configuration
# ============================================================

N_BINS = 22

PIE_MIN = 0.01
PIE_MAX = 20.0

MIN_COUNT_PER_CLASS = 30

NOMINAL_COVERAGE = 0.68

WILSON_Z = 1.959963984540054


# ============================================================
# Helpers
# ============================================================

def numeric(
    df,
    column,
):

    return pd.to_numeric(
        df[column],
        errors="coerce",
    ).to_numpy(
        dtype=float
    )


def wilson_interval(
    successes,
    total,
    z=WILSON_Z,
):

    if total <= 0:

        return (
            np.nan,
            np.nan,
        )

    p = (
        successes
        / total
    )

    z2 = (
        z * z
    )

    denominator = (
        1.0
        + z2 / total
    )

    center = (
        p
        + z2
        / (
            2.0
            * total
        )
    ) / denominator

    half_width = (
        z
        / denominator
        * np.sqrt(
            p
            * (
                1.0
                - p
            )
            / total
            + z2
            / (
                4.0
                * total
                * total
            )
        )
    )

    return (
        center
        - half_width,
        center
        + half_width,
    )


# ============================================================
# Main
# ============================================================

def main():

    if not INPUT.exists():

        raise FileNotFoundError(
            f"Input not found:\n{INPUT}"
        )

    FIGURE_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    RESULT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    df = pd.read_parquet(
        INPUT,
        columns=[
            "catalog_row",
            "positive_lrt_class",
            "piE_true_amp",
            "mc_valid_covariance",
            "mc_q16_piE_amp",
            "mc_q50_piE_amp",
            "mc_q84_piE_amp",
        ],
    )

    piE_true = numeric(
        df,
        "piE_true_amp",
    )

    q16 = numeric(
        df,
        "mc_q16_piE_amp",
    )

    q50 = numeric(
        df,
        "mc_q50_piE_amp",
    )

    q84 = numeric(
        df,
        "mc_q84_piE_amp",
    )

    classes = df[
        "positive_lrt_class"
    ].astype(
        str
    ).to_numpy()

    valid_covariance = df[
        "mc_valid_covariance"
    ].fillna(
        False
    ).to_numpy(
        dtype=bool
    )

    # ========================================================
    # Valid central intervals
    # ========================================================

    valid = (
        valid_covariance
        & np.isfinite(
            piE_true
        )
        & (
            piE_true > 0
        )
        & np.isfinite(
            q16
        )
        & np.isfinite(
            q50
        )
        & np.isfinite(
            q84
        )
        & (
            q16 <= q50
        )
        & (
            q50 <= q84
        )
    )

    covered = np.zeros(
        len(df),
        dtype=bool,
    )

    covered[
        valid
    ] = (
        (
            piE_true[
                valid
            ]
            >= q16[
                valid
            ]
        )
        & (
            piE_true[
                valid
            ]
            <= q84[
                valid
            ]
        )
    )

    confused = (
        classes
        == "confused_fspl_no_parallax"
    )

    detected = (
        classes
        == "parallax_detected"
    )

    # ========================================================
    # Overall class-conditional coverage
    # ========================================================

    print(
        "=" * 105
    )

    print(
        "EMPIRICAL COVERAGE OF MC 68% |pi_E| INTERVAL"
    )

    print(
        "=" * 105
    )

    print()

    print(
        "rows =",
        len(df),
    )

    print(
        "valid MC intervals =",
        int(
            valid.sum()
        ),
    )

    print(
        "invalid =",
        int(
            (~valid).sum()
        ),
    )

    print()

    regions = {
        "confused_fspl_no_parallax":
            confused,

        "parallax_detected":
            detected,
    }

    summary_rows = []

    for class_name, class_mask in (
        regions.items()
    ):

        use = (
            valid
            & class_mask
        )

        n = int(
            use.sum()
        )

        n_covered = int(
            np.sum(
                covered[
                    use
                ]
            )
        )

        coverage = (
            n_covered
            / n
        )

        lower, upper = (
            wilson_interval(
                n_covered,
                n,
            )
        )

        summary_rows.append(
            {
                "class":
                    class_name,

                "n":
                    n,

                "n_covered":
                    n_covered,

                "coverage68":
                    coverage,

                "wilson95_lower":
                    lower,

                "wilson95_upper":
                    upper,
            }
        )

    summary = pd.DataFrame(
        summary_rows
    )

    print(
        summary.to_string(
            index=False
        )
    )

    # ========================================================
    # Coverage versus TRUE |pi_E|
    # ========================================================

    edges = np.geomspace(
        PIE_MIN,
        PIE_MAX,
        N_BINS + 1,
    )

    rows = []

    for ibin in range(
        N_BINS
    ):

        left = edges[
            ibin
        ]

        right = edges[
            ibin + 1
        ]

        if ibin == N_BINS - 1:

            in_bin = (
                valid
                & (
                    piE_true
                    >= left
                )
                & (
                    piE_true
                    <= right
                )
            )

        else:

            in_bin = (
                valid
                & (
                    piE_true
                    >= left
                )
                & (
                    piE_true
                    < right
                )
            )

        center = np.sqrt(
            left
            * right
        )

        for class_name, class_mask in (
            regions.items()
        ):

            use = (
                in_bin
                & class_mask
            )

            n = int(
                use.sum()
            )

            if n:

                n_covered = int(
                    np.sum(
                        covered[
                            use
                        ]
                    )
                )

                coverage = (
                    n_covered
                    / n
                )

                lower, upper = (
                    wilson_interval(
                        n_covered,
                        n,
                    )
                )

            else:

                n_covered = 0
                coverage = np.nan
                lower = np.nan
                upper = np.nan

            rows.append(
                {
                    "bin_index":
                        ibin,

                    "class":
                        class_name,

                    "piE_true_left":
                        left,

                    "piE_true_right":
                        right,

                    "piE_true_center":
                        center,

                    "n":
                        n,

                    "n_covered":
                        n_covered,

                    "coverage68":
                        coverage,

                    "wilson95_lower":
                        lower,

                    "wilson95_upper":
                        upper,

                    "shown_in_figure":
                        (
                            n
                            >= MIN_COUNT_PER_CLASS
                        ),
                }
            )

    result = pd.DataFrame(
        rows
    )

    result.to_csv(
        TABLE,
        index=False,
    )

    # ========================================================
    # Figure
    # ========================================================

    fig, ax = plt.subplots(
        figsize=(6.8, 4.4)
    )

    for class_name in [
        "confused_fspl_no_parallax",
        "parallax_detected",
    ]:

        sub = result.loc[
            (
                result[
                    "class"
                ]
                == class_name
            )
            & result[
                "shown_in_figure"
            ]
        ].copy()

        x = sub[
            "piE_true_center"
        ].to_numpy(
            dtype=float
        )

        y = sub[
            "coverage68"
        ].to_numpy(
            dtype=float
        )

        lower = sub[
            "wilson95_lower"
        ].to_numpy(
            dtype=float
        )

        upper = sub[
            "wilson95_upper"
        ].to_numpy(
            dtype=float
        )

        good = (
            np.isfinite(x)
            & np.isfinite(y)
            & np.isfinite(lower)
            & np.isfinite(upper)
        )

        label = (
            "Confused with FSPL without parallax"
            if class_name
            == "confused_fspl_no_parallax"
            else "Parallax detected"
        )

        line, = ax.plot(
            x[
                good
            ],
            y[
                good
            ],
            marker="o",
            markersize=4.0,
            linewidth=1.5,
            label=label,
        )

        ax.fill_between(
            x[
                good
            ],
            lower[
                good
            ],
            upper[
                good
            ],
            alpha=0.18,
            color=line.get_color(),
        )

    ax.axhline(
        NOMINAL_COVERAGE,
        linestyle="--",
        linewidth=1.1,
        label="Nominal central 68% interval",
    )

    ax.set_xscale(
        "log"
    )

    ax.set_xlim(
        PIE_MIN,
        PIE_MAX,
    )

    ax.set_ylim(
        0.0,
        1.0,
    )

    ax.set_xlabel(
        r"True $|\boldsymbol{\pi}_E|$"
    )

    ax.set_ylabel(
        (
            r"$P("
            r"q_{16}\leq"
            r"|\boldsymbol{\pi}_{E,\rm true}|"
            r"\leq q_{84}"
            r")$"
        )
    )


    ax.grid(
        alpha=0.25,
    )

    ax.legend(
        fontsize=13,
    )


    fig.savefig(
        FIGURE,
        dpi=300,
        bbox_inches="tight",
    )
    save_pdf_companion(fig, FIGURE)

    print()

    print(
        "Saved figure:",
        FIGURE,
    )

    print(
        "Saved bins:",
        TABLE,
    )


if __name__ == "__main__":
    main()


