#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Coverage of the lens-mass interval obtained by propagating the local
parallax-vector covariance while theta_E is fixed to truth.

NO simulation.
NO fitting.
NO new Monte Carlo.

The MC draws of |pi_E| were already generated by script 22.
Because M_L is a monotonic transformation of pi_E for fixed theta_E,

    M_L propto 1/pi_E,

the transformed central interval is

    [M_q16, M_q84]
        =
    [C / piE_q84, C / piE_q16].

The first figure shows 68% mass-interval coverage versus true pi_E,
separately for confused and detected events.

The second figure shows, for confused events, whether the true mass is

    below the interval,
    inside the interval,
    above the interval.

This makes the direction of the mass failure explicit.
"""

from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# Paths
# ============================================================

ROOT = Path(__file__).resolve().parents[3]

INPUT = (
    ROOT
    / "analysis/lrt/results/characterization"
    / "39_lens_mass_parallax_only"
    / "lens_mass_parallax_only_events.parquet"
)

FIGURE_DIR = (
    ROOT
    / "analysis/lrt/figures/characterization"
    / "41_lens_mass_mc_coverage_vs_truth"
)

RESULT_DIR = (
    ROOT
    / "analysis/lrt/results/characterization"
    / "41_lens_mass_mc_coverage_vs_truth"
)

COVERAGE_PNG = (
    FIGURE_DIR
    / "lens_mass_mc_coverage_vs_true_piE.png"
)

COVERAGE_PDF = (
    FIGURE_DIR
    / "lens_mass_mc_coverage_vs_true_piE.pdf"
)

OUTCOMES_PNG = (
    FIGURE_DIR
    / "confused_lens_mass_mc_interval_outcomes.png"
)

OUTCOMES_PDF = (
    FIGURE_DIR
    / "confused_lens_mass_mc_interval_outcomes.pdf"
)

COVERAGE_TABLE = (
    RESULT_DIR
    / "lens_mass_mc_coverage_vs_true_piE_bins.csv"
)

OUTCOMES_TABLE = (
    RESULT_DIR
    / "confused_lens_mass_mc_interval_outcomes_bins.csv"
)

SUMMARY_FILE = (
    RESULT_DIR
    / "lens_mass_mc_coverage_summary.txt"
)


# ============================================================
# Configuration
# ============================================================

N_BINS = 22
MIN_COUNT = 30

NOMINAL_COVERAGE = 0.6826894921370859

CLASSES = [
    "confused_fspl_no_parallax",
    "parallax_detected",
]

CLASS_LABELS = {
    "confused_fspl_no_parallax":
        "Confused with no-parallax FSPL",

    "parallax_detected":
        "Parallax detected",
}


# ============================================================
# Style
# ============================================================

def set_paper_style():

    plt.rcParams.update(
        {
            "font.size": 16,
            "axes.labelsize": 19,
            "axes.titlesize": 18,
            "legend.fontsize": 13,

            "xtick.labelsize": 15,
            "ytick.labelsize": 15,

            "axes.linewidth": 0.9,
            "lines.linewidth": 1.8,

            "xtick.direction": "in",
            "ytick.direction": "in",

            "xtick.top": True,
            "ytick.right": True,

            "savefig.dpi": 300,
            "savefig.bbox": "tight",

            "mathtext.fontset": "stix",
            "font.family": "STIXGeneral",
        }
    )


# ============================================================
# Helpers
# ============================================================

def numeric(df, column):

    return pd.to_numeric(
        df[column],
        errors="coerce",
    ).to_numpy(dtype=float)


def make_log_edges(values, n_bins):

    values = np.asarray(
        values,
        dtype=float,
    )

    valid = (
        np.isfinite(values)
        & (values > 0.0)
    )

    if not np.any(valid):
        raise RuntimeError(
            "No positive finite values for binning."
        )

    vmin = float(
        np.nanmin(values[valid])
    )

    vmax = float(
        np.nanmax(values[valid])
    )

    edges = np.geomspace(
        vmin,
        vmax,
        n_bins + 1,
    )

    edges[0] = np.nextafter(
        vmin,
        -np.inf,
    )

    edges[-1] = np.nextafter(
        vmax,
        np.inf,
    )

    return edges


def wilson_interval(k, n, z=1.959963984540054):

    if n <= 0:
        return np.nan, np.nan

    p = k / n

    denominator = (
        1.0
        + z * z / n
    )

    center = (
        p
        + z * z / (2.0 * n)
    ) / denominator

    half = (
        z
        * np.sqrt(
            p * (1.0 - p) / n
            + z * z / (4.0 * n * n)
        )
        / denominator
    )

    return (
        center - half,
        center + half,
    )


# ============================================================
# Main
# ============================================================

def main():

    set_paper_style()

    FIGURE_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    RESULT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    if not INPUT.exists():
        raise FileNotFoundError(
            INPUT
        )

    df = pd.read_parquet(
        INPUT
    )

    required = [
        "positive_lrt_class",
        "lens_mass_true_msun",
        "piE_true_amp",
        "mass_mc_valid",
        "mass_mc_q16_msun",
        "mass_mc_q84_msun",
        "mass_mc_covered",
    ]

    missing = [
        col
        for col in required
        if col not in df.columns
    ]

    if missing:
        raise RuntimeError(
            f"Missing columns: {missing}"
        )

    classes = (
        df["positive_lrt_class"]
        .astype(str)
        .to_numpy()
    )

    mass_true = numeric(
        df,
        "lens_mass_true_msun",
    )

    piE_true = numeric(
        df,
        "piE_true_amp",
    )

    q16_mass = numeric(
        df,
        "mass_mc_q16_msun",
    )

    q84_mass = numeric(
        df,
        "mass_mc_q84_msun",
    )

    mc_valid = (
        df["mass_mc_valid"]
        .fillna(False)
        .to_numpy(dtype=bool)
    )

    covered = (
        df["mass_mc_covered"]
        .fillna(False)
        .to_numpy(dtype=bool)
    )

    valid = (
        mc_valid
        & np.isfinite(piE_true)
        & (piE_true > 0.0)
        & np.isfinite(mass_true)
        & (mass_true > 0.0)
        & np.isfinite(q16_mass)
        & np.isfinite(q84_mass)
        & (q16_mass > 0.0)
        & (q84_mass >= q16_mass)
    )

    edges = make_log_edges(
        piE_true[valid],
        N_BINS,
    )

    # ========================================================
    # Coverage bins
    # ========================================================

    coverage_rows = []

    for cls in CLASSES:

        class_mask = (
            classes
            == cls
        )

        for ibin in range(
            len(edges) - 1
        ):

            left = edges[ibin]
            right = edges[ibin + 1]

            mask = (
                valid
                & class_mask
                & (piE_true >= left)
                & (piE_true < right)
            )

            n = int(
                mask.sum()
            )

            k = int(
                covered[mask].sum()
            )

            fraction = (
                k / n
                if n > 0
                else np.nan
            )

            lo, hi = wilson_interval(
                k,
                n,
            )

            coverage_rows.append(
                {
                    "class": cls,
                    "bin_index": ibin,
                    "piE_left": left,
                    "piE_right": right,
                    "piE_center": np.sqrt(
                        left * right
                    ),
                    "n": n,
                    "n_covered": k,
                    "coverage": fraction,
                    "wilson_low": lo,
                    "wilson_high": hi,
                }
            )

    coverage_table = pd.DataFrame(
        coverage_rows
    )

    coverage_table.to_csv(
        COVERAGE_TABLE,
        index=False,
    )

    # ========================================================
    # Figure 1: coverage
    # ========================================================

    fig, ax = plt.subplots(
        figsize=(8.0, 5.6)
    )

    for cls in CLASSES:

        sub = coverage_table[
            (coverage_table["class"] == cls)
            & (coverage_table["n"] >= MIN_COUNT)
        ].copy()

        if len(sub) == 0:
            continue

        line, = ax.plot(
            sub["piE_center"],
            sub["coverage"],
            marker="o",
            markersize=4.5,
            label=CLASS_LABELS[cls],
        )

        ax.fill_between(
            sub["piE_center"],
            sub["wilson_low"],
            sub["wilson_high"],
            alpha=0.20,
            color=line.get_color(),
        )

    ax.axhline(
        NOMINAL_COVERAGE,
        linestyle="--",
        linewidth=1.4,
        color="black",
        label=r"Nominal $68.27\%$",
    )

    ax.set_xscale(
        "log"
    )

    ax.set_ylim(
        0.0,
        1.02,
    )

    ax.set_xlabel(
        r"True $|\boldsymbol{\pi}_E|$"
    )

    ax.set_ylabel(
        "Lens-mass interval coverage"
    )

    ax.set_title(
        r"Coverage of the central $68\%$ lens-mass interval"
    )

    ax.grid(
        True,
        alpha=0.20,
    )

    ax.legend(
        frameon=True,
    )

    fig.tight_layout()

    fig.savefig(
        COVERAGE_PNG
    )

    fig.savefig(
        COVERAGE_PDF
    )

    plt.close(
        fig
    )

    # ========================================================
    # Confused-event interval outcomes
    # ========================================================

    confused = (
        classes
        == "confused_fspl_no_parallax"
    )

    outcomes_rows = []

    for ibin in range(
        len(edges) - 1
    ):

        left = edges[ibin]
        right = edges[ibin + 1]

        mask = (
            valid
            & confused
            & (piE_true >= left)
            & (piE_true < right)
        )

        n = int(
            mask.sum()
        )

        if n > 0:

            truth_below = int(
                np.sum(
                    mass_true[mask]
                    < q16_mass[mask]
                )
            )

            truth_inside = int(
                np.sum(
                    (mass_true[mask] >= q16_mass[mask])
                    & (mass_true[mask] <= q84_mass[mask])
                )
            )

            truth_above = int(
                np.sum(
                    mass_true[mask]
                    > q84_mass[mask]
                )
            )

        else:

            truth_below = 0
            truth_inside = 0
            truth_above = 0

        outcomes_rows.append(
            {
                "bin_index": ibin,
                "piE_left": left,
                "piE_right": right,
                "piE_center": np.sqrt(
                    left * right
                ),
                "n": n,
                "truth_below_n": truth_below,
                "truth_inside_n": truth_inside,
                "truth_above_n": truth_above,
                "truth_below_fraction":
                    truth_below / n
                    if n > 0
                    else np.nan,
                "truth_inside_fraction":
                    truth_inside / n
                    if n > 0
                    else np.nan,
                "truth_above_fraction":
                    truth_above / n
                    if n > 0
                    else np.nan,
            }
        )

    outcomes_table = pd.DataFrame(
        outcomes_rows
    )

    outcomes_table.to_csv(
        OUTCOMES_TABLE,
        index=False,
    )

    shown = outcomes_table[
        outcomes_table["n"]
        >= MIN_COUNT
    ].copy()

    fig, ax = plt.subplots(
        figsize=(8.0, 5.6)
    )

    ax.plot(
        shown["piE_center"],
        shown["truth_below_fraction"],
        marker="o",
        label="True mass below interval",
    )

    ax.plot(
        shown["piE_center"],
        shown["truth_inside_fraction"],
        marker="o",
        label="True mass inside interval",
    )

    ax.plot(
        shown["piE_center"],
        shown["truth_above_fraction"],
        marker="o",
        label="True mass above interval",
    )

    ax.set_xscale(
        "log"
    )

    ax.set_ylim(
        0.0,
        1.02,
    )

    ax.set_xlabel(
        r"True $|\boldsymbol{\pi}_E|$"
    )

    ax.set_ylabel(
        "Fraction of confused events"
    )

    ax.set_title(
        "Lens-mass interval outcomes for confused events"
    )

    ax.grid(
        True,
        alpha=0.20,
    )

    ax.legend(
        frameon=True,
    )

    fig.tight_layout()

    fig.savefig(
        OUTCOMES_PNG
    )

    fig.savefig(
        OUTCOMES_PDF
    )

    plt.close(
        fig
    )

    # ========================================================
    # Global class summary
    # ========================================================

    lines = []

    lines.append(
        "LENS-MASS MC COVERAGE"
    )

    lines.append(
        "=" * 80
    )

    for cls in CLASSES:

        mask = (
            valid
            & (classes == cls)
        )

        n = int(
            mask.sum()
        )

        k = int(
            covered[mask].sum()
        )

        coverage = (
            k / n
            if n > 0
            else np.nan
        )

        lines.append("")
        lines.append(cls)
        lines.append(
            f"N valid = {n:,}"
        )
        lines.append(
            f"N covered = {k:,}"
        )
        lines.append(
            f"coverage = {coverage:.6f}"
        )

        if cls == "confused_fspl_no_parallax" and n > 0:

            n_below = int(
                np.sum(
                    mass_true[mask]
                    < q16_mass[mask]
                )
            )

            n_above = int(
                np.sum(
                    mass_true[mask]
                    > q84_mass[mask]
                )
            )

            lines.append(
                "truth below interval = "
                f"{n_below / n:.6f}"
            )

            lines.append(
                "truth above interval = "
                f"{n_above / n:.6f}"
            )

    summary = "\n".join(
        lines
    )

    SUMMARY_FILE.write_text(
        summary + "\n"
    )

    print(summary)

    print()
    print("Saved:")
    print(COVERAGE_PNG)
    print(COVERAGE_PDF)
    print(OUTCOMES_PNG)
    print(OUTCOMES_PDF)
    print(COVERAGE_TABLE)
    print(OUTCOMES_TABLE)
    print(SUMMARY_FILE)


if __name__ == "__main__":
    main()
